/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
//
//Base addr for RCC - 0x40023800
//Offset - 0x30
//mask - (1<<3) enable AHB1ENR
//Base addr for GPIOD - 0x40020C00
//Offset - 0x00 mode
//mask - (1<<0x8000000)
//
//Offset - 0x04 type
//mask - (1<<0x00008000)
//
//Offset - 0x08 speed
//mask - (1<<0x80000000)
//
//Offset - 0x0C pullup pull down
//mask - (1<<8000000)
//
//Offset - 0x14 output data register (odr)
//mask
// on - |= (1<<0x00008000)
// off - &= ~(1<<0x0008000)
//////////////////////////////////


int main(void)
{
	uint32_t *rcc = (uint32_t*) 0x40023830;
	uint32_t *GPIOD_mode = (uint32_t*) 0x40020C00;
	uint32_t *GPIOD_type = (uint32_t*) 0x40020C04;
	uint32_t *GPIOD_speed = (uint32_t*) 0x40020C08;
	uint32_t *GPIOD_pupd = (uint32_t*) 0x40020C0C;
	uint32_t *GPIOD_odr = (uint32_t*) 0x40020C14;


	//Enable AHB1ENR
	*rcc |= (1<<3);
	//Set up general output speed pullup pulldown
	*GPIOD_mode |= (1<<30);
	*GPIOD_type |= (0<<15);
	*GPIOD_speed |= (1<<31);
	*GPIOD_pupd |=(1<<31);
	//
    /* Loop forever */
	*GPIOD_odr ^= (1<<15);
}
